<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CuLkmqK.App\Controller\AvisController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CuLkmqK.App\\Controller\\AvisController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avi' => ['privates', '.errored..service_locator.CuLkmqK.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.CuLkmqK": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avi' => 'App\\Entity\\Avis',
        ]))->withContext('App\\Controller\\AvisController::show()', $container);
    }
}
