<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllercreateReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OcNFIUf.App\Controller\PassagerController::createReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OcNFIUf.App\\Controller\\PassagerController::createReservation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonce' => ['privates', '.errored..service_locator.OcNFIUf.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.OcNFIUf": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'badWordsFilter' => ['privates', 'App\\Service\\BadWordsFilter', 'getBadWordsFilterService', true],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
            'entityManager' => '?',
            'badWordsFilter' => 'App\\Service\\BadWordsFilter',
        ]))->withContext('App\\Controller\\PassagerController::createReservation()', $container);
    }
}
