<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XBvUCal.App\Controller\PassagerController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XBvUCal.App\\Controller\\PassagerController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'eventParticipationRepository' => ['privates', 'App\\Repository\\EventParticipationRepository', 'getEventParticipationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'eventParticipationRepository' => 'App\\Repository\\EventParticipationRepository',
        ]))->withContext('App\\Controller\\PassagerController::dashboard()', $container);
    }
}
