<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPricePredictionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PricePredictionService' shared autowired service.
     *
     * @return \App\Service\PricePredictionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PricePredictionService.php';

        return $container->privates['App\\Service\\PricePredictionService'] = new \App\Service\PricePredictionService(($container->privates['App\\Service\\MapService'] ?? $container->load('getMapServiceService')));
    }
}
