knpu_oauth2_client:
    clients:
        # configure your clients as described in the docs
        # https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '307828071606-rmof12g67hhvlpj0920mqv8p3o86rs17.apps.googleusercontent.com'
            client_secret: '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'
            redirect_route: connect_google_check
            redirect_params: {}
            # SSL verification is handled at application level 