admin_reclamations:
    path: /admin/reclamations
    controller: App\Controller\Admin\ReclamationController::index
    methods: GET
    
admin_reclamations_show:
    path: /admin/reclamations/{id}
    controller: App\Controller\Admin\ReclamationController::show
    methods: [GET, POST]
    
admin_reclamations_resolve:
    path: /admin/reclamations/{id}/resolve
    controller: App\Controller\Admin\ReclamationController::resolve
    methods: POST 

# Route supplémentaire pour debug
admin_reclamation:
    path: /admin/reclamation
    controller: App\Controller\Admin\ReclamationController::index
    methods: GET 