<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxaSxhv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxaSxhv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxaSxhv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxaSxhv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxaSxhv\App_KernelDevDebugContainer([
    'container.build_hash' => 'DxaSxhv',
    'container.build_id' => '68b31e8b',
    'container.build_time' => 1745885715,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxaSxhv');
