<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AvisController' shared autowired service.
     *
     * @return \App\Controller\AvisController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AvisController'] = $instance = new \App\Controller\AvisController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\AvisController', $container));

        return $instance;
    }
}
