<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceEvent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.edhxnJg.App\Entity\AnnonceEvent' shared service.
     *
     * @return \App\Entity\AnnonceEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.edhxnJg": it needs an instance of "App\\Entity\\AnnonceEvent" but this type has been excluded in "config/services.yaml".');
    }
}
