<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceEventControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gA8ax55.App\Controller\Admin\AnnonceEventController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gA8ax55.App\\Controller\\Admin\\AnnonceEventController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEvent' => ['privates', '.errored..service_locator.gA8ax55.App\\Entity\\AnnonceEvent', NULL, 'Cannot autowire service ".service_locator.gA8ax55": it needs an instance of "App\\Entity\\AnnonceEvent" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'userRepository' => ['privates', '.errored.yaAnTCP', NULL, 'Cannot determine controller argument for "App\\Controller\\Admin\\AnnonceEventController::edit()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UserRepository".'],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
        ], [
            'annonceEvent' => 'App\\Entity\\AnnonceEvent',
            'entityManager' => '?',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'userRepository' => '?',
            'carRepository' => 'App\\Repository\\CarRepository',
        ]))->withContext('App\\Controller\\Admin\\AnnonceEventController::edit()', $container);
    }
}
