<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonce2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6o72F3G.App\Entity\Annonce' shared service.
     *
     * @return \App\Entity\Annonce
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6o72F3G": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".');
    }
}
