<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CvlC7bO.App\Controller\AvisController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.CvlC7bO'] ?? $container->load('get_ServiceLocator_CvlC7bOService'));

        if (isset($container->privates['.service_locator.CvlC7bO.App\\Controller\\AvisController::edit()'])) {
            return $container->privates['.service_locator.CvlC7bO.App\\Controller\\AvisController::edit()'];
        }

        return $container->privates['.service_locator.CvlC7bO.App\\Controller\\AvisController::edit()'] = $a->withContext('App\\Controller\\AvisController::edit()', $container);
    }
}
