<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerterminerEventAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7NLNQ7E.App\Controller\ConducteurController::terminerEventAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7NLNQ7E.App\\Controller\\ConducteurController::terminerEventAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ConducteurController::terminerEventAnnonce()', $container);
    }
}
