<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllergetCarModelsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9pPm.Ki.App\Controller\ConducteurController::getCarModels()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9pPm.Ki.App\\Controller\\ConducteurController::getCarModels()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carApiService' => ['privates', 'App\\Service\\CarApiService', 'getCarApiServiceService', true],
        ], [
            'carApiService' => 'App\\Service\\CarApiService',
        ]))->withContext('App\\Controller\\ConducteurController::getCarModels()', $container);
    }
}
