<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CarApiService' shared autowired service.
     *
     * @return \App\Service\CarApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\CarApiService'] = new \App\Service\CarApiService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
