<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerreservationsEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vECtGew.App\Controller\ConducteurController::reservationsEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vECtGew.App\\Controller\\ConducteurController::reservationsEvent()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\ConducteurController::reservationsEvent()', $container);
    }
}
