<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllereditVoitureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qKzwST1.App\Controller\ConducteurController::editVoiture()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qKzwST1.App\\Controller\\ConducteurController::editVoiture()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'carApiService' => ['privates', 'App\\Service\\CarApiService', 'getCarApiServiceService', true],
        ], [
            'entityManager' => '?',
            'carRepository' => 'App\\Repository\\CarRepository',
            'carApiService' => 'App\\Service\\CarApiService',
        ]))->withContext('App\\Controller\\ConducteurController::editVoiture()', $container);
    }
}
