<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.thLAep..App\Controller\ConducteurController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.thLAep..App\\Controller\\ConducteurController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'carRepository' => 'App\\Repository\\CarRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\ConducteurController::dashboard()', $container);
    }
}
