<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllermodifierTrajetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qyHYwMG.App\Controller\ConducteurController::modifierTrajet()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qyHYwMG.App\\Controller\\ConducteurController::modifierTrajet()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajet' => ['privates', '.errored..service_locator.qyHYwMG.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.qyHYwMG": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".'],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
            'carRepository' => 'App\\Repository\\CarRepository',
        ]))->withContext('App\\Controller\\ConducteurController::modifierTrajet()', $container);
    }
}
