<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllerconversationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sQJ3USz.App\Controller\ChatController::conversations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sQJ3USz.App\\Controller\\ChatController::conversations()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
        ]))->withContext('App\\Controller\\ChatController::conversations()', $container);
    }
}
