<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControlleraccepterReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y655hhB.App\Controller\ConducteurController::accepterReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y655hhB.App\\Controller\\ConducteurController::accepterReservation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.Y655hhB.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.Y655hhB": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'entityManager' => '?',
            'emailService' => 'App\\Service\\EmailService',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]))->withContext('App\\Controller\\ConducteurController::accepterReservation()', $container);
    }
}
