<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerlisteAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._fiEl.2.App\Controller\ConducteurController::listeAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._fiEl.2.App\\Controller\\ConducteurController::listeAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
            'carRepository' => 'App\\Repository\\CarRepository',
        ]))->withContext('App\\Controller\\ConducteurController::listeAnnonce()', $container);
    }
}
