<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIpGeoLocationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\IpGeoLocationService' shared autowired service.
     *
     * @return \App\Service\IpGeoLocationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\IpGeoLocationService'] = new \App\Service\IpGeoLocationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
