<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerlisteAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.asiU0_Q.App\Controller\PassagerController::listeAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.asiU0_Q.App\\Controller\\PassagerController::listeAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'ipGeoLocationService' => ['privates', 'App\\Service\\IpGeoLocationService', 'getIpGeoLocationServiceService', true],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
            'ipGeoLocationService' => 'App\\Service\\IpGeoLocationService',
        ]))->withContext('App\\Controller\\PassagerController::listeAnnonce()', $container);
    }
}
