<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllermodifierAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.reumqAC.App\Controller\PassagerController::modifierAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.reumqAC.App\\Controller\\PassagerController::modifierAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonce' => ['privates', '.errored..service_locator.reumqAC.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.reumqAC": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".'],
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
        ]))->withContext('App\\Controller\\PassagerController::modifierAnnonce()', $container);
    }
}
