<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerrechercherParPositionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3jTXIET.App\Controller\PassagerController::rechercherParPosition()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3jTXIET.App\\Controller\\PassagerController::rechercherParPosition()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ipGeoLocationService' => ['privates', 'App\\Service\\IpGeoLocationService', 'getIpGeoLocationServiceService', true],
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
        ], [
            'ipGeoLocationService' => 'App\\Service\\IpGeoLocationService',
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
        ]))->withContext('App\\Controller\\PassagerController::rechercherParPosition()', $container);
    }
}
