<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceControllerpredictPriceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hfWyVnY.App\Controller\PriceController::predictPrice()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hfWyVnY.App\\Controller\\PriceController::predictPrice()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pricePredictionService' => ['privates', 'App\\Service\\PricePredictionService', 'getPricePredictionServiceService', true],
        ], [
            'pricePredictionService' => 'App\\Service\\PricePredictionService',
        ]))->withContext('App\\Controller\\PriceController::predictPrice()', $container);
    }
}
