<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllereventAnnoncesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Py876X9.App\Controller\PassagerController::eventAnnonces()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Py876X9.App\\Controller\\PassagerController::eventAnnonces()'] = ($container->privates['.service_locator.Py876X9'] ?? $container->load('get_ServiceLocator_Py876X9Service'))->withContext('App\\Controller\\PassagerController::eventAnnonces()', $container);
    }
}
