<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationResponseTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ReclamationResponseType' shared autowired service.
     *
     * @return \App\Form\ReclamationResponseType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReclamationResponseType'] = new \App\Form\ReclamationResponseType(($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
