<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TrajetRepository' shared autowired service.
     *
     * @return \App\Repository\TrajetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TrajetRepository'] = new \App\Repository\TrajetRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
