<?php

namespace Container5dc9SPb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qS6acth.App\Controller\Admin\TrajetController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qS6acth.App\\Controller\\Admin\\TrajetController::show()'] = ($container->privates['.service_locator.qS6acth'] ?? $container->load('get_ServiceLocator_QS6acthService'))->withContext('App\\Controller\\Admin\\TrajetController::show()', $container);
    }
}
