<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceEventControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.edhxnJg.App\Controller\Admin\AnnonceEventController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.edhxnJg.App\\Controller\\Admin\\AnnonceEventController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEvent' => ['privates', '.errored..service_locator.edhxnJg.App\\Entity\\AnnonceEvent', NULL, 'Cannot autowire service ".service_locator.edhxnJg": it needs an instance of "App\\Entity\\AnnonceEvent" but this type has been excluded in "config/services.yaml".'],
        ], [
            'annonceEvent' => 'App\\Entity\\AnnonceEvent',
        ]))->withContext('App\\Controller\\Admin\\AnnonceEventController::show()', $container);
    }
}
