<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllersendMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DrH8BAB.App\Controller\ChatController::sendMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.DrH8BAB'] ?? $container->load('get_ServiceLocator_DrH8BABService'));

        if (isset($container->privates['.service_locator.DrH8BAB.App\\Controller\\ChatController::sendMessage()'])) {
            return $container->privates['.service_locator.DrH8BAB.App\\Controller\\ChatController::sendMessage()'];
        }

        return $container->privates['.service_locator.DrH8BAB.App\\Controller\\ChatController::sendMessage()'] = $a->withContext('App\\Controller\\ChatController::sendMessage()', $container);
    }
}
