<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WP4vSSy.App\Controller\ConducteurController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WP4vSSy.App\\Controller\\ConducteurController::dashboard()'] = ($container->privates['.service_locator.WP4vSSy'] ?? $container->load('get_ServiceLocator_WP4vSSyService'))->withContext('App\\Controller\\ConducteurController::dashboard()', $container);
    }
}
