<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerannulerParticipationEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JTsBDHu.App\Controller\PassagerController::annulerParticipationEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JTsBDHu.App\\Controller\\PassagerController::annulerParticipationEvent()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'participationRepository' => ['privates', 'App\\Repository\\EventParticipationRepository', 'getEventParticipationRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'participationRepository' => 'App\\Repository\\EventParticipationRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PassagerController::annulerParticipationEvent()', $container);
    }
}
