<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerparticiperEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xI132Nr.App\Controller\PassagerController::participerEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xI132Nr.App\\Controller\\PassagerController::participerEvent()'] = ($container->privates['.service_locator.xI132Nr'] ?? $container->load('get_ServiceLocator_XI132NrService'))->withContext('App\\Controller\\PassagerController::participerEvent()', $container);
    }
}
