<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllerchangeStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m7PCOb4.App\Controller\Admin\ReclamationController::changeStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m7PCOb4.App\\Controller\\Admin\\ReclamationController::changeStatus()'] = ($container->privates['.service_locator.m7PCOb4'] ?? $container->load('get_ServiceLocator_M7PCOb4Service'))->withContext('App\\Controller\\Admin\\ReclamationController::changeStatus()', $container);
    }
}
