<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRideControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdcJSTP.App\Controller\RideController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LdcJSTP.App\\Controller\\RideController::show()'] = ($container->privates['.service_locator.LdcJSTP'] ?? $container->load('get_ServiceLocator_LdcJSTPService'))->withContext('App\\Controller\\RideController::show()', $container);
    }
}
