<?php

namespace ContainerDxaSxhv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllershow2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z6hnZpb.App\Controller\ReclamationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z6hnZpb.App\\Controller\\ReclamationController::show()'] = ($container->privates['.service_locator.Z6hnZpb'] ?? $container->load('get_ServiceLocator_Z6hnZpbService'))->withContext('App\\Controller\\ReclamationController::show()', $container);
    }
}
