<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annonceEvents' => [parent::class, 'annonceEvents', null],
        "\0".parent::class."\0".'dateEvent' => [parent::class, 'dateEvent', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'heureEvent' => [parent::class, 'heureEvent', null],
        "\0".parent::class."\0".'idEvent' => [parent::class, 'idEvent', null],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'participations' => [parent::class, 'participations', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'typeEvent' => [parent::class, 'typeEvent', null],
        'annonceEvents' => [parent::class, 'annonceEvents', null],
        'dateEvent' => [parent::class, 'dateEvent', null],
        'description' => [parent::class, 'description', null],
        'heureEvent' => [parent::class, 'heureEvent', null],
        'idEvent' => [parent::class, 'idEvent', null],
        'lieu' => [parent::class, 'lieu', null],
        'nom' => [parent::class, 'nom', null],
        'participations' => [parent::class, 'participations', null],
        'status' => [parent::class, 'status', null],
        'typeEvent' => [parent::class, 'typeEvent', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
