<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \App\Entity\Annonce implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'available_seats' => [parent::class, 'available_seats', null],
        "\0".parent::class."\0".'car_id' => [parent::class, 'car_id', null],
        "\0".parent::class."\0".'date_publication' => [parent::class, 'date_publication', null],
        "\0".parent::class."\0".'date_termination' => [parent::class, 'date_termination', null],
        "\0".parent::class."\0".'departureDate' => [parent::class, 'departureDate', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'driver_id' => [parent::class, 'driver_id', null],
        "\0".parent::class."\0".'event_id' => [parent::class, 'event_id', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        "\0".parent::class."\0".'trajet' => [parent::class, 'trajet', null],
        'available_seats' => [parent::class, 'available_seats', null],
        'car_id' => [parent::class, 'car_id', null],
        'date_publication' => [parent::class, 'date_publication', null],
        'date_termination' => [parent::class, 'date_termination', null],
        'departureDate' => [parent::class, 'departureDate', null],
        'description' => [parent::class, 'description', null],
        'driver_id' => [parent::class, 'driver_id', null],
        'event_id' => [parent::class, 'event_id', null],
        'id' => [parent::class, 'id', null],
        'reservations' => [parent::class, 'reservations', null],
        'status' => [parent::class, 'status', null],
        'titre' => [parent::class, 'titre', null],
        'trajet' => [parent::class, 'trajet', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
