<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Py876X9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Py876X9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Py876X9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
        ]);
    }
}
