<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z6hnZpbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z6hnZpb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z6hnZpb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamation' => ['privates', '.errored..service_locator.Z6hnZpb.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.Z6hnZpb": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reclamation' => 'App\\Entity\\Reclamation',
        ]);
    }
}
