<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceEventControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X_ZY0h_.App\Controller\Admin\AnnonceEventController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X_ZY0h_.App\\Controller\\Admin\\AnnonceEventController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEvent' => ['privates', '.errored..service_locator.X_ZY0h_.App\\Entity\\AnnonceEvent', NULL, 'Cannot autowire service ".service_locator.X_ZY0h_": it needs an instance of "App\\Entity\\AnnonceEvent" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonceEvent' => 'App\\Entity\\AnnonceEvent',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Admin\\AnnonceEventController::delete()', $container);
    }
}
