<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllerterminateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6o72F3G.App\Controller\Admin\AnnonceController::terminate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6o72F3G'] ?? $container->load('get_ServiceLocator_6o72F3GService'));

        if (isset($container->privates['.service_locator.6o72F3G.App\\Controller\\Admin\\AnnonceController::terminate()'])) {
            return $container->privates['.service_locator.6o72F3G.App\\Controller\\Admin\\AnnonceController::terminate()'];
        }

        return $container->privates['.service_locator.6o72F3G.App\\Controller\\Admin\\AnnonceController::terminate()'] = $a->withContext('App\\Controller\\Admin\\AnnonceController::terminate()', $container);
    }
}
