<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ht8IwBt.App\Controller\Admin\AnnonceController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ht8IwBt.App\\Controller\\Admin\\AnnonceController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonce' => ['privates', '.errored..service_locator.ht8IwBt.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.ht8IwBt": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".'],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
        ]))->withContext('App\\Controller\\Admin\\AnnonceController::show()', $container);
    }
}
