<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllermodifierAnnonceSubmitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.45_08Pv.App\Controller\ConducteurController::modifierAnnonceSubmit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.45_08Pv.App\\Controller\\ConducteurController::modifierAnnonceSubmit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonce' => ['privates', '.errored..service_locator.45_08Pv.App\\Entity\\Annonce', NULL, 'Cannot autowire service ".service_locator.45_08Pv": it needs an instance of "App\\Entity\\Annonce" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
        ], [
            'annonce' => 'App\\Entity\\Annonce',
            'entityManager' => '?',
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
            'carRepository' => 'App\\Repository\\CarRepository',
        ]))->withContext('App\\Controller\\ConducteurController::modifierAnnonceSubmit()', $container);
    }
}
