<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllergetNewMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5r2SZ.m.App\Controller\ChatController::getNewMessages()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5r2SZ.m.App\\Controller\\ChatController::getNewMessages()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]))->withContext('App\\Controller\\ChatController::getNewMessages()', $container);
    }
}
