<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerparticipationsParraineesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RsEaryP.App\Controller\ConducteurController::participationsParrainees()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.RsEaryP'] ?? $container->load('get_ServiceLocator_RsEaryPService'));

        if (isset($container->privates['.service_locator.RsEaryP.App\\Controller\\ConducteurController::participationsParrainees()'])) {
            return $container->privates['.service_locator.RsEaryP.App\\Controller\\ConducteurController::participationsParrainees()'];
        }

        return $container->privates['.service_locator.RsEaryP.App\\Controller\\ConducteurController::participationsParrainees()'] = $a->withContext('App\\Controller\\ConducteurController::participationsParrainees()', $container);
    }
}
