<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerannonceSubmitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pd7cmlC.App\Controller\ConducteurController::annonceSubmit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Pd7cmlC'] ?? $container->load('get_ServiceLocator_Pd7cmlCService'));

        if (isset($container->privates['.service_locator.Pd7cmlC.App\\Controller\\ConducteurController::annonceSubmit()'])) {
            return $container->privates['.service_locator.Pd7cmlC.App\\Controller\\ConducteurController::annonceSubmit()'];
        }

        return $container->privates['.service_locator.Pd7cmlC.App\\Controller\\ConducteurController::annonceSubmit()'] = $a->withContext('App\\Controller\\ConducteurController::annonceSubmit()', $container);
    }
}
