<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wxPd78M.App\Controller\EventController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wxPd78M.App\\Controller\\EventController::show()'] = ($container->privates['.service_locator.wxPd78M'] ?? $container->load('get_ServiceLocator_WxPd78MService'))->withContext('App\\Controller\\EventController::show()', $container);
    }
}
