<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerlisteAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdcJSTP.App\Controller\PassagerController::listeAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LdcJSTP.App\\Controller\\PassagerController::listeAnnonce()'] = ($container->privates['.service_locator.LdcJSTP'] ?? $container->load('get_ServiceLocator_LdcJSTPService'))->withContext('App\\Controller\\PassagerController::listeAnnonce()', $container);
    }
}
