<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerannulerReservationEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DrH8BAB.App\Controller\PassagerController::annulerReservationEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DrH8BAB.App\\Controller\\PassagerController::annulerReservationEvent()'] = ($container->privates['.service_locator.DrH8BAB'] ?? $container->load('get_ServiceLocator_DrH8BABService'))->withContext('App\\Controller\\PassagerController::annulerReservationEvent()', $container);
    }
}
