<?php

namespace ContainerOURwFJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControllerupdateAllStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..TB14Su.App\Controller\Admin\ReclamationController::updateAllStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..TB14Su.App\\Controller\\Admin\\ReclamationController::updateAllStatus()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Admin\\ReclamationController::updateAllStatus()', $container);
    }
}
