<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k4oezbb.App\Controller\AvisController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k4oezbb.App\\Controller\\AvisController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'twig' => '?',
        ]))->withContext('App\\Controller\\AvisController::list()', $container);
    }
}
