<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceEventControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yfv4ICY.App\Controller\Admin\AnnonceEventController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yfv4ICY.App\\Controller\\Admin\\AnnonceEventController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
        ], [
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
        ]))->withContext('App\\Controller\\Admin\\AnnonceEventController::index()', $container);
    }
}
