<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerterminerAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6o72F3G.App\Controller\ConducteurController::terminerAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6o72F3G.App\\Controller\\ConducteurController::terminerAnnonce()'] = ($container->privates['.service_locator.6o72F3G'] ?? $container->load('get_ServiceLocator_6o72F3GService'))->withContext('App\\Controller\\ConducteurController::terminerAnnonce()', $container);
    }
}
