<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerajouterAnnonceSubmitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sIP3HQJ.App\Controller\ConducteurController::ajouterAnnonceSubmit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sIP3HQJ.App\\Controller\\ConducteurController::ajouterAnnonceSubmit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
        ], [
            'entityManager' => '?',
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
            'carRepository' => 'App\\Repository\\CarRepository',
        ]))->withContext('App\\Controller\\ConducteurController::ajouterAnnonceSubmit()', $container);
    }
}
