<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllereditEventAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NprmiGt.App\Controller\ConducteurController::editEventAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NprmiGt.App\\Controller\\ConducteurController::editEventAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
            'carRepository' => 'App\\Repository\\CarRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ConducteurController::editEventAnnonce()', $container);
    }
}
