<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerreservationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5EVliFN.App\Controller\ConducteurController::reservations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5EVliFN'] ?? $container->load('get_ServiceLocator_5EVliFNService'));

        if (isset($container->privates['.service_locator.5EVliFN.App\\Controller\\ConducteurController::reservations()'])) {
            return $container->privates['.service_locator.5EVliFN.App\\Controller\\ConducteurController::reservations()'];
        }

        return $container->privates['.service_locator.5EVliFN.App\\Controller\\ConducteurController::reservations()'] = $a->withContext('App\\Controller\\ConducteurController::reservations()', $container);
    }
}
