<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerdeleteEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xI132Nr.App\Controller\ConducteurController::deleteEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xI132Nr'] ?? $container->load('get_ServiceLocator_XI132NrService'));

        if (isset($container->privates['.service_locator.xI132Nr.App\\Controller\\ConducteurController::deleteEvent()'])) {
            return $container->privates['.service_locator.xI132Nr.App\\Controller\\ConducteurController::deleteEvent()'];
        }

        return $container->privates['.service_locator.xI132Nr.App\\Controller\\ConducteurController::deleteEvent()'] = $a->withContext('App\\Controller\\ConducteurController::deleteEvent()', $container);
    }
}
