<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControlleraddVoitureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JIPD.Nh.App\Controller\ConducteurController::addVoiture()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JIPD.Nh.App\\Controller\\ConducteurController::addVoiture()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'carApiService' => ['privates', 'App\\Service\\CarApiService', 'getCarApiServiceService', true],
        ], [
            'entityManager' => '?',
            'carApiService' => 'App\\Service\\CarApiService',
        ]))->withContext('App\\Controller\\ConducteurController::addVoiture()', $container);
    }
}
