<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllereventParticipantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iQ4Cx52.App\Controller\ConducteurController::eventParticipants()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iQ4Cx52.App\\Controller\\ConducteurController::eventParticipants()'] = ($container->privates['.service_locator.iQ4Cx52'] ?? $container->load('get_ServiceLocator_IQ4Cx52Service'))->withContext('App\\Controller\\ConducteurController::eventParticipants()', $container);
    }
}
