<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllereditEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ghZcH.5.App\Controller\ConducteurController::editEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ghZcH.5.App\\Controller\\ConducteurController::editEvent()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'typeEventRepository' => ['privates', 'App\\Repository\\TypeEventRepository', 'getTypeEventRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'typeEventRepository' => 'App\\Repository\\TypeEventRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ConducteurController::editEvent()', $container);
    }
}
