<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllerconversationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RTaB4Eb.App\Controller\ChatController::conversation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RTaB4Eb.App\\Controller\\ChatController::conversation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ChatController::conversation()', $container);
    }
}
