<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllerrefuserReservationEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jJvfXQK.App\Controller\ConducteurController::refuserReservationEvent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jJvfXQK.App\\Controller\\ConducteurController::refuserReservationEvent()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
        ]))->withContext('App\\Controller\\ConducteurController::refuserReservationEvent()', $container);
    }
}
