<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConducteurControllercreateEventAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t61sIE7.App\Controller\ConducteurController::createEventAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t61sIE7.App\\Controller\\ConducteurController::createEventAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'carRepository' => 'App\\Repository\\CarRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ConducteurController::createEventAnnonce()', $container);
    }
}
