<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllersubmitAvisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5EVliFN.App\Controller\PassagerController::submitAvis()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5EVliFN.App\\Controller\\PassagerController::submitAvis()'] = ($container->privates['.service_locator.5EVliFN'] ?? $container->load('get_ServiceLocator_5EVliFNService'))->withContext('App\\Controller\\PassagerController::submitAvis()', $container);
    }
}
