<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPassagerControllerreserverEventAnnonceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AU2NOYP.App\Controller\PassagerController::reserverEventAnnonce()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AU2NOYP.App\\Controller\\PassagerController::reserverEventAnnonce()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'badWordsFilter' => ['privates', 'App\\Service\\BadWordsFilter', 'getBadWordsFilterService', true],
        ], [
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
            'entityManager' => '?',
            'badWordsFilter' => 'App\\Service\\BadWordsFilter',
        ]))->withContext('App\\Controller\\PassagerController::reserverEventAnnonce()', $container);
    }
}
