<?php

namespace ContainerN3Kaxdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kQ7OTWj.App\Controller\Admin\ReservationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kQ7OTWj.App\\Controller\\Admin\\ReservationController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.kQ7OTWj.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.kQ7OTWj": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'annonceEventRepository' => ['privates', 'App\\Repository\\AnnonceEventRepository', 'getAnnonceEventRepositoryService', true],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UtilisateurRepository',
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
            'annonceEventRepository' => 'App\\Repository\\AnnonceEventRepository',
        ]))->withContext('App\\Controller\\Admin\\ReservationController::edit()', $container);
    }
}
